#!/bin/sh

internetConnection()
{
   my_ip=$(/usr/bin/wget --timeout=3 -q -O - http://icanhazip.com/ | /usr/bin/tail)

   if [ -z "$my_ip" ] 
   then
      internet="No";
   else
      internet="Si";
   fi
}

internetConnection

## Black        0;30     Dark Gray     1;30
## Red          0;31     Light Red     1;31
## Green        0;32     Light Green   1;32
## Brown/Orange 0;33     Yellow        1;33
## Blue         0;34     Light Blue    1;34
## Purple       0;35     Light Purple  1;35
## Cyan         0;36     Light Cyan    1;36
## Light Gray   0;37     White         1;37

color1='\033[1;31m'    # light red
color2='\033[1;35m'    # light purple
color3='\033[0;33m'    # light yellow
color4='\033[1;37m'    # White
color5='\033[1;33m'    # Yellow

nocolor='\033[0m'      # no color
companyname='\033[1;34mUniversidad de Oviedo.\033[0m'
divisionname='\033[1;32mMaquina Ubuntu para Asignaturas del Proyecto "Cobra Kali"\033[0m'

printf "               ${color1}.-.${nocolor}\n"
printf "         ${color2}.-'\`\`${color1}(   )    ${companyname}${nocolor}\n"
printf "      ${color3},\`\\ ${color2}\\    ${color1}\`-\`${color2}.    ${divisionname}${nocolor}\n"
printf "     ${color3}/   \\ ${color2}'\`\`-.   \`\n"
printf "   ${color2}.-.  ${color3},       ${color2}\`___:  ${color4}MV Ubuntu 22.04 XFCE4 (Cores: `cat /proc/cpuinfo | grep processor | wc -l`, RAM: `grep MemTotal /proc/meminfo | awk '{print $2 / 1024}'`Mb)${nocolor}\n"
printf "  ${color2}(   ) ${color3}:       ${color1} ___   ${nocolor}`date +"%A, %d/%m/%Y, %r"`${nocolor}\n"
printf "   ${color2}\`-\`  ${color3}\`      ${color1} ,   :${nocolor} ${color1} HACK FIRST, HACK HARD, NO MERCY! ${nocolor}\n"
printf "     ${color3}\\   / ${color1},..-\`   ,${color4}\n"
printf "      ${color3}\`./${color1} /    ${color3}.-.${color1}\`${color4}    Directorio actual: `pwd`\n"
printf "         ${color1}\`-..-${color3}(   )${nocolor}    ¿Tienes Internet?: ${internet}\n"
printf "               ${color3}\`-\`${nocolor}\n"
printf "\n"
printf "${color5}¿Quieres un GUI? Ejecuta ${color4}startx${color5}. ¿Necesitas ayuda sobre un comando en el GUI? Ejecuta ${color4}gman${color5} y buscalo\n"
printf "¿No quieres GUI y necesitas mas terminales? Haz ${color4}Alt+F2, F3, etc.${color5} o ejecuta ${color4}tmux${color5}. \n¿Necesitas un explorador de archivos? Ejecuta ${color4}mc${color5}\n"
printf "¿No tienes ni idea de que comando usar para algo? Ejecuta ${color4}apropos <lo que quieres hacer>${color5} y mira las opciones que te da${nocolor}\n"
